name: Auto Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        with:
          default_branch: 'main'
