name: Auto Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        with:
          npm-args: "--unsafe-perm --allow-same-version"
          default_branch: 'main'
