name: Publish To NPM
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
  
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/


      - name: Install and Build
         run: |
         npm install
         npm run-script build

      - name: Publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.CLEAR_PLUGIN_NPM_TOKEN}} 
        run: npm publish